### PR TITLE
Added class for suit

### PR DESCRIPTION
**Pull request by 80cmdude**
Whatcha think

### CODE REVIEW

**Comment by ordinaryashen** [comment]
dench, but I **think** we might be able to get; set; each card instead of construct the suit.

**Comment by 80cmdude** [comment]
Was thinking that but then its gonna be a pain to merge into hearts//spades etc?

**Comment by ordinaryashen** [comment]
hearts, spades, clubs and diamond constructors with the private properties used for each of them... i think.
Oh yeah and we could have ace as a bool with 1 || 11 instead of true || false... but im not too sure.

**Comment by 80cmdude** [comment]
But then we have to declare variables 4 times right? which seems like a bit of a waste of time? Yeah im leave Ace as 1 for now to keep it as simple as poss. MVP and all

**Comment by ordinaryashen** [comment]
we could keep it this way then inherit the suit class into hearts, diamond,
spades and clubs classes?
ᐧ

On 21 June 2016 at 14:43, 80cmdude notifications@github.com wrote:

> But then we have to declare variables 4 times right? which seems like a
> bit of a waste of time? Yeah im leave Ace as 1 for now to keep it as simple
> as poss. MVP and all
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/80cmdude/Blackjack/pull/2#issuecomment-227443453, or mute
> the thread
> https://github.com/notifications/unsubscribe/AQzISGs9sybKZnExvPWyPNqxEImCV3thks5qN-p4gaJpZM4I6uZH
> .

## 

Ashley Henry | Digital Apprentice
Dragon Court, 27-29 Macklin Street, London, WC2B 5LX
Tel: 020 7067 4646   Ext: 416
[image: reed.co.uk] http://www.reed.co.uk/
The UK's #1 job site. http://www.reed.co.uk/
[image: Follow us on Twitter] https://twitter.com/reedcouk
https://www.linkedin.com/company/reed.co.uk [image: Like us on Facebook]
https://www.facebook.com/reedcouk/
https://plus.google.com/u/0/+reedcouk/posts
It's time to Love Mondays » http://www.reed.co.uk/lovemondays

## 

Reed Online Ltd is a company registered in England and Wales. Company 
Registration Number: 6317279.
Registered Office: Academy Court, 94 Chancery Lane, London WC2A 1DT.

**Comment by 80cmdude** [comment]
That was my plan since i didnt wanna write the same code 4 times.. But its diff trying to decide what way to do it when you are starting out.. trying to keep as simple as poss

**Comment by ordinaryashen** [comment]
hm well lets keep it how it is!

inheritance sounds good to me
ᐧ

On 21 June 2016 at 14:47, 80cmdude notifications@github.com wrote:

> That was my plan since i didnt wanna write the same code 4 times.. But its
> diff trying to decide what way to do it when you are starting out.. trying
> to keep as simple as poss
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/80cmdude/Blackjack/pull/2#issuecomment-227444680, or mute
> the thread
> https://github.com/notifications/unsubscribe/AQzISFhvY-sIOr3SUmIg-UKpBw4-0HGUks5qN-tugaJpZM4I6uZH
> .

## 

Ashley Henry | Digital Apprentice
Dragon Court, 27-29 Macklin Street, London, WC2B 5LX
Tel: 020 7067 4646   Ext: 416
[image: reed.co.uk] http://www.reed.co.uk/
The UK's #1 job site. http://www.reed.co.uk/
[image: Follow us on Twitter] https://twitter.com/reedcouk
https://www.linkedin.com/company/reed.co.uk [image: Like us on Facebook]
https://www.facebook.com/reedcouk/
https://plus.google.com/u/0/+reedcouk/posts
It's time to Love Mondays » http://www.reed.co.uk/lovemondays

## 

Reed Online Ltd is a company registered in England and Wales. Company 
Registration Number: 6317279.
Registered Office: Academy Court, 94 Chancery Lane, London WC2A 1DT.

**Comment by 80cmdude** [comment]
im merging

**Pull request merged**
